### ISSUE TITLE
Returning empty results seems not to work.

### ISSUE THREAD

**Issue by ruedih** [secureCodeBox/scanner-webapplication-zap#5]
There is a 400 Bad request if zap returns failures with empty results back to the engine.

**Comment by rseedorff** [comment]
@j12934 I guess this issue should be fixed with the latest improvements you have committed regarding the engine API

**Comment by J12934** [comment]
No, i fixed issues with endpoint always returning 404 statuses.
This is most likely related to Zap sending error messages which are incompatible with the validation rules of the failure endpoint.
I'll look into it.

**Comment by rseedorff** [comment]
Is this still an issue that we should take into account?

**Comment by J12934** [comment]
Should be fixed with the changes made to the zap wrapper.
If this still happens please let us know.
